#1. 튜플

* 리스트와 비슷하지만 리스트는 []로 자료를 감싸고, 튜플은 ()로 감쌈
* 수정 및 삭제가 불가능

In [11]:
tu1= ()
print(tu1)

#tu1[0] = 10  #TypeError: 'tuple' object does not support item assignment

tu2 = (1, 3, 5, 7)
print(tu2)

tu3 = 1, 3, 5, 7
print(tu3)

tu4 = ('apple', 'banana', ('🍔', '🍟'))
print(tu4)

tu5 = ('apple', 'banana', ['🍔', '🍟'])  #튜플 안에 리스트는 가능 
print(tu5)

print(type(tu5))

()
(1, 3, 5, 7)
(1, 3, 5, 7)
('apple', 'banana', ('🍔', '🍟'))
('apple', 'banana', ['🍔', '🍟'])
<class 'tuple'>

#2. 튜플의 수정과 삭제

In [9]:
tu6 = (1, 2, 'apple', 'banana')
print(tu6)

#tu6[3] = 'orange'  #TypeError: 'tuple' object does not support item assignment
#del tu6[3]  #TypeError: 'tuple' object doesn't support item deletion
del tu6  #튜플 자체는 삭제 가능 
#print(tu6)  #TypeError: 'tuple' object doesn't support item deletion

(1, 2, 'apple', 'banana')

NameError: ignored

In [10]:
tu7 = (1, 2, 'apple', 'banana')
print(tu7)

tu7 = [1, 2, 'apple', 'banana']  #주소/타입을 바꾸는것은 가능하다 
print(tu7)
print(type(tu7))

(1, 2, 'apple', 'banana')
[1, 2, 'apple', 'banana']
<class 'list'>

#3, 튜플의 인덱싱과 슬라이싱 연산

In [12]:
tu8 = (1, 2, 'apple', 'banana')

# 인덱싱
print(tu8[0])
print(tu8[-1])

# 슬라이싱
print(tu8[1:])
print(tu8[1:3])

# 덧셈(연결)
tu9 = (30, 40)
print(tu8 + tu9)

# 곱셈(반복)
print(tu8 * 3)

# 요소의 갯수
print(len(tu8))

1
banana
(2, 'apple', 'banana')
(2, 'apple')
(1, 2, 'apple', 'banana', 30, 40)
(1, 2, 'apple', 'banana', 1, 2, 'apple', 'banana', 1, 2, 'apple', 'banana')
4