#1. 리스트 List

* 자료구조란? 자료(데이터)를 어떤 형태로 담을지 정하는것 
* 리스트는 여러가지 데이터를 ,(콤마)로 구분하여 []로 감싼 자료구조 
* 자료의 데이터 타입이 다르더라도 같이 저장이 가능

In [ ]:
li1 = [1, 3, 5, 7] #literal 구조; 이용하기 편리하게 
print(li1)

li2 = list([1, 3, 5, 7])  #클래스를 이용한 객체를 만든다; 이것이 원칙 
print(li2)

li3 = ['김사과', '오렌지', '반하나', '이메론']
print(li3)

li4 = [1, 1.5, '김사과', True]  #타입이 다른 데이터도 저장 가능 
print(li4)

li5 = [1, 2, '파이썬', ['김사과', '오렌지']]
print(li5)

[1, 3, 5, 7]
[1, 3, 5, 7]
['김사과', '오렌지', '반하나', '이메론']
[1, 1.5, '김사과', True]
[1, 2, '파이썬', ['김사과', '오렌지']]

#2. 리스트 인덱싱

In [ ]:
li1 = [1, 3, 5, 7]
print(li1[0])
print(li1[-1])
print(li1[0] + li1 [-1])

1
7
8

In [ ]:
li2 = ['김사과', '오렌지', '반하나', ['🍎','🍊','🍌']]
print(li2[-1])
print(li2[-1][1])

['🍎', '🍊', '🍌']
🍊

In [ ]:
li3 = [1, 3, 5, ['김사과', '오렌지', '반하나', ['🍎','🍊','🍌']]]
print(li3[-2]) #5
print(li3[2]) #5
print(li3[-1][-2]) #반하나 
print(li3[-1][-1][-1])

5
5
반하나
🍌

#3. 리스트 슬라이싱

In [ ]:
li4 = [10, 20, 30, 40, 50]
print(li4)
print(type(li4)) #<class 'list'>
print(li4[0:3])

li5 = li4 
print(li5)
li5[0] = 100
print(li5)
print(li4) 

li6 = [10, 20, 30, ['김사과', '오렌지', '반하나'], 40, ['🍔', '🍟']]
print(li6)
print(li6[5][:1])

[10, 20, 30, 40, 50]
<class 'list'>
[10, 20, 30]
[10, 20, 30, 40, 50]
[100, 20, 30, 40, 50]
[100, 20, 30, 40, 50]
[10, 20, 30, ['김사과', '오렌지', '반하나'], 40, ['🍔', '🍟']]
['🍔']

#4. 리스트 연산자

In [ ]:
li7 = [10, 20, 30]
li8 = [40, 50, 60]

print(li7 + li8) #[10, 20, 30, 40, 50, 60]; 리스트 안에 있는 스칼라들을 더하는게 아니라 가져다 붙히는 개념 
print(li8 + li7) #[40, 50, 60, 10, 20, 30]
#print (li7 - li8) #그래서 뺄셈은 안됨 
print(li7 * 3) #[10, 20, 30, 10, 20, 30, 10, 20, 30]; 가져다 붙히는 개념이라서 세번 반복
print('🖤' * 30)

li9 = [10, 20 ,30]
li9[1] = '🖤'
print(li9)
#print(li9[0] + li9[1]) #TypeError: unsupported operand type(s) for +: 'int' and 'str'
print(li9[0] + li9[2])

[10, 20, 30, 40, 50, 60]
[40, 50, 60, 10, 20, 30]
[10, 20, 30, 10, 20, 30, 10, 20, 30]
🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤
[10, '🖤', 30]
40

#5. 리스트의 수정/삭제

In [ ]:
li10 = [10, 20, 30]
li10[1] = 100
print (li10)

li10[1:2] = ['🥝', '🍇', '🍓']  #주의! 슬라이싱을 이용하여 데이트를 변경한 경우 리스트에 데이터가 포함 
print(li10)

li10 = [10, 20, 30]
li10[1] = ['🥝', '🍇', '🍓']  #주의! 인덱싱을 이용하여 데이터를 변경한 경우 리스트 **안에**  리스트가 포함 
print(li10)

print(li10[0:3])
li10[1:3] = [] #요소 삭제
print(li10)

del li10[0]
print(li10)

[10, 100, 30]
[10, '🥝', '🍇', '🍓', 30]
[10, ['🥝', '🍇', '🍓'], 30]
[10, ['🥝', '🍇', '🍓'], 30]
[10]
[]

#6. 리스트 함수

* 객체란 .함수

In [ ]:
li11 = [10, 20, 30]

# append() : 리스트의 마지막 자리에 데이터를 추가 
li11.append(100)
print(li11)

li11.append([40, 50]) #리스트 안에 리스트가 추가 
print(li11)

[10, 20, 30, 100]
[10, 20, 30, 100, [40, 50]]

In [ ]:
li12 = [10, 20, 30, 40, 50]

# pop() : 리스트에 마지막에 저장된 데이터를 반환하고 해당 데이트 삭제
print(li12) 
temp = li12. pop() #temp에 50이란 숫자가 저장이 되고, li12에는 50이라는 요소가 사라짐 
print(temp)
print(li12)
li12.pop() # 이 경우엔 마지막 데이터가 그냥 날라가서 복구 X
print(li12)

# side notes: 마지막에 있는 걸 다른곳에 저장해두고 다시 복원 시킬때는 append 사용

[10, 20, 30, 40, 50]
50
[10, 20, 30, 40]
[10, 20, 30]

In [ ]:
li13 = [10, 20, 30, 10, 20, 80]

# remove() : 매개변수로 전달된 데이터를 제거. 같은 데이터가 여러개가 잇는 경우 처음 출연하는 데이터 제거 
li13.remove(20)
print(li13)

li13.remove(20)
print(li13)

#li13.remove(20) #ValueError: list.remove(x): x not in list

[10, 30, 10, 20, 80]
[10, 30, 10, 80]

In [ ]:
li14 = [10, 20, 30]

# insert() : 리스트의 특정 위치에 데이터 삽입
li14.insert(1, 100) #[10, 100, 20, 30]; 1인덱스 데이터 100을 삽입 후 나머지 인덱스는 그 뒤로 밀림 
print(li14)

li14.insert(1, (100, 200))
print(li14)

[10, 100, 20, 30]
[10, (100, 200), 100, 20, 30]

In [ ]:
li15 = [10, 20, 30, 40, 50]

# index() : 리스트에 저장된 데이터가 존재할 경우 위치를 인덱스로 전환 
print(li15.index(30))
#print(li15.index(100)) #ValueError: 100 is not in list

2

In [ ]:
li16 = ['김시과', '오렌지', '반하나', '이메론']

# reverse() : 리스트에 저장된 데이터를 반대의 순서로 반환 
li16.reverse()
print(li16)

#일부 구간만 reverse를 하고 싶을땐 > 슬라이싱으로 뽑은 후에 > temp 변수에 구간 저장후 > reverse 시키고 > 다시 원래의 변수에 대입

['이메론', '반하나', '오렌지', '김시과']

In [ ]:
li17 = [10, 40, 30, 100, 90, 50]

# sort() : 리스트에 저장된 데이터를 정렬; 정렬된 바뀐 데이터를 저장함!! 저장을 하느냐 안하느냐가 중요 
li17.sort()  # 오름차순
print(li17)

# sort(reverse=True)  #내림차순
li17.sort(reverse=True)
print(li17)

li18=['Apple', 'apple', 'orange', 'banana', 'Banana', 'melon', '10', '#', '안녕', '김치'] 
li18.sort() # 아스키코드 
print(li18)

[10, 30, 40, 50, 90, 100]
[100, 90, 50, 40, 30, 10]
['#', '10', 'Apple', 'Banana', 'apple', 'banana', 'melon', 'orange', '김치', '안녕']

In [ ]:
li19 = [10, 20, 30, 50, 20, 40, 30, 20]

# count() : 리스트에 포함된 특정 데이터의 개수를 반환
print(li19.count(20))
print(li19.count(15))

3
0

In [ ]:
li20 = [1, 2, 3]

# extend() : 리스트를 더함 
li21 = [1 ,2, 3]
li21 = li21 + [40, 50]
print(li21)

[1, 2, 3, 40, 50]